=== dglo/stf-gen1/private/stf-apps/stfDefn.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://glacier.lbl.gov/icecube/daq/stf" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="test">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="version">
          <xs:complexType>
            <xs:attribute name="major" type="xs:nonNegativeInteger" use="required"/>
            <xs:attribute name="minor" type="xs:nonNegativeInteger" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="inputParameter">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:choice>
                <xs:element name="boolean">
                  <xs:complexType>
                    <xs:attribute name="default" type="xs:boolean" use="required"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="string">
                  <xs:complexType>
                    <xs:attribute name="default" type="xs:string" use="required"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="unsignedInt">
                  <xs:complexType>
                    <xs:attribute name="minValue" type="xs:unsignedInt" use="required"/>
                    <xs:attribute name="maxValue" type="xs:unsignedInt" use="required"/>
                    <xs:attribute name="default" type="xs:unsignedInt" use="required"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="unsignedLong">
                  <xs:complexType>
                     <xs:attribute name="minValue" type="xs:unsignedLong" use="required"/>
                    <xs:attribute name="maxValue" type="xs:unsignedLong" use="required"/>
                    <xs:attribute name="default" type="xs:unsignedLong" use="required"/>
                 </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="outputParameter">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:choice>
                <xs:element name="boolean">
                  <xs:complexType/>
                </xs:element>
                <xs:element name="string">
                  <xs:complexType/>
                </xs:element>
                <xs:element name="unsignedInt">
                  <xs:complexType/>
                </xs:element>
                <xs:element name="unsignedLong">
                  <xs:complexType/>
                </xs:element>
              </xs:choice>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dglo/stf-gen1/private/stf-apps/pressure.xml
<?xml version="1.0" encoding="UTF-8"?>
<stf:test xmlns:stf="http://glacier.lbl.gov/icecube/daq/stf"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://glacier.lbl.gov/icecube/daq/stf file:/Volumes/IceCube/WorkSpaces/daq/stf/private/stf-apps/stfDefn.xsd">
  <name>pressure</name>
  <description>Test the ADC channel corresponding to the pressure gauge</description>
  <version major="1" minor="0"/>
  <inputParameter>
    <description>Board is sealed in sphere</description>
    <name>dom_sealed</name>
    <boolean default="True"/>
  </inputParameter>

  <inputParameter>
    <description>Temperature gauge reading is used in pass criteria.</description>
    <name>use_temperature</name>
    <boolean default="False"/>
  </inputParameter>

  <inputParameter>
    <description>Number of ADC values to acquire to compute a mean and spread</description>
    <name>loop_count</name>
    <unsignedInt default="1000" minValue="0" maxValue="1000000"/>
  </inputParameter>

  <outputParameter>
    <description>Mean of the 5volt ADC values in millivolts</description>
    <name>adc_5v_mean_mvolts</name>
    <unsignedInt/>
  </outputParameter>

   <outputParameter>
    <description>Mean of the ADC values distribution in count units</description>
    <name>adc_mean_counts</name>
    <unsignedInt/>
  </outputParameter>

  <outputParameter>
    <description>Spread of the ADC values distribution in count units</description>
    <name>adc_rms_counts</name>
    <unsignedInt/>
  </outputParameter>

  <outputParameter>
    <description>Maximum of the ADC values distribution in count units</description>
    <name>adc_max_counts</name>
    <unsignedInt/>
  </outputParameter>

  <outputParameter>
    <description>Minimum of the ADC values distribution in count units</description>
    <name>adc_min_counts</name>
    <unsignedInt/>
  </outputParameter>

  <outputParameter>
    <description>Mean of the ADC values distribution in kPascal units</description>
    <name>adc_mean_kpascal</name>
    <unsignedInt/>
  </outputParameter>

  <outputParameter>
    <description>Spread of the ADC values distribution in kPascal units</description>
    <name>adc_rms_kpascal</name>
    <unsignedInt/>
  </outputParameter>

  <outputParameter>
    <description>Maximum of the ADC values distribution in kPascal units</description>
    <name>adc_max_kpascal</name>
    <unsignedInt/>
  </outputParameter>

  <outputParameter>
    <description>Minimum of the ADC values distribution in kPascal units</description>
    <name>adc_min_kpascal</name>
    <unsignedInt/>
  </outputParameter>
</stf:test>

=== dglo/stf-gen1/private/stf-apps/fadc_fe_external.xml
<?xml version="1.0" encoding="UTF-8"?>
<stf:test xmlns:stf="http://glacier.lbl.gov/icecube/daq/stf"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://glacier.lbl.gov/icecube/daq/stf file:/Volumes/IceCube/WorkSpaces/daq/stf/private/stf-apps/stfDefn.xsd">
  <name>fadc_fe_external</name>
  <description>Test the STF FADC FE external PULSER</description>
  <version major="1" minor="0"/>
<!--    <fpgaDependencies>
        <COM_FIFO/>
        <DAQ/>
        <PULSERS/>
        <DISCRIMINATOR_RATE/>
        <LOCAL_COINC/>
        <FLASHER_BOARD/>
        <TRIGGER/>
        <LOCAL_CLOCK/>
        <SUPERNOVA/>
    </fpgaDependencies>  -->
  <inputParameter>
    <description>10 bit DAC setting for FADC reference voltage</description>
    <name>fadc_reference_dac</name>
    <unsignedInt default="700" minValue="0" maxValue="1023"/>
  </inputParameter>

  <inputParameter>
    <description>12Bit DAC setting for atwd pedestal voltage </description>
    <name>atwd_pedestal_dac</name>
    <unsignedInt  default="1925" minValue="0" maxValue="4095"/>
  </inputParameter>

  <inputParameter>
    <description>First value of the SPE DAC that was above noise(of 10bit)if no trigger point then use last tried point</description>
    <name>triggerable_spe_dac</name>
    <unsignedInt default="455" minValue="0" maxValue="5000"/>
  </inputParameter>

  <inputParameter>
    <description>Number of waveforms to take and average over before analysis.</description>
    <name>loop_count</name>
    <unsignedInt default="100" minValue="0" maxValue="1000000"/>
  </inputParameter>

  <outputParameter>
    <description>Amplitude of the positive going pulse (in FADC count units.)</description>
    <name>fadc_fe_pulser_amplitude</name>
    <unsignedInt/>
  </outputParameter>

  <outputParameter>
    <description>Width of the positive going pulse ( in FADC samples = 2x clock counts).</description>
    <name>fadc_fe_pulser_width</name>
    <unsignedInt/>
  </outputParameter>

  <outputParameter>
    <description>Position of the triggered positive going pulse (in FADC samples - 2x clock counts).</description>
    <name>fadc_fe_pulser_position</name>
    <unsignedInt/>
  </outputParameter>

  <outputParameter>
    <description>Average waveform FADC baseline values in ATWD counts units.</description>
    <name>fadc_fe_pulser_waveform</name>
    <unsignedIntArray length="512"/>
  </outputParameter>

</stf:test>
